services:
  database:
    image: postgres:18.2-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - "./docker/db/postgresql:/var/lib/postgresql/data"
    ports:
      - "5532:${DATABASE_PORT}"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"

  php:
    build:
      context: ./docker/php
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x php-fpm > /dev/null || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - ".:/var/www/html"
      - "~/.composer:/home/docker/.composer"
      - "~/.ssh:/home/docker/.ssh"
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:1.29.5-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ".:/var/www/html"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      php:
        condition: service_healthy

  mailer:
    image: axllent/mailpit
    ports:
      - "1125:1025"
      - "1180:8025"
