version: '3.8'

services:
  database:
    image: postgres:15
    restart: "no"
    healthcheck:
      test: "/etc/init.d/postgresql status"
      timeout: 1s
      retries: 60
    volumes:
      - "./docker/db/postgresql:/var/lib/postgresql/data"
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"

  php:
    build:
      context: ./docker/php
    tty: true
    restart: "no"
    volumes:
      - ".:/var/www/html"
      - "~/.composer:/home/docker/.composer"
      - "~/.ssh:/home/docker/.ssh"
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8180:80'
    volumes:
      - ".:/var/www/html"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - database

  mailer:
    image: schickling/mailcatcher
    ports:
    - "1125:1025"
    - "1180:1080"

  nodejs:
    build:
      context: ./docker/nodejs
    user: "${HOST_UID}:${HOST_GROUP_ID}"
    volumes:
      - ".:/app"
